name: Linter
on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Download config files from Massa testnet branch
        uses: wei/wget@v1
        with:
          args: -P ./external -i ./external/config-files.txt
      - name: Install sphinx-lint
        run: pip install sphinx-lint
      - name: Run sphinx-lint
        run: sphinx-lint --enable line-too-long --max-line-length 120
      - name: Run sphinx-build lint
        run: make html SPHINXOPTS="-W --keep-going -n"
