name: Linter
on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Download config files from Massa testnet branch
        run: |
         wget -N -P ./external/node/ -i ./external/node/config-files.txt &&
         wget -N -P ./external/client/ -i ./external/client/config-files.txt
      - name: Install sphinx-lint
        run: pip install sphinx-lint
      - name: Run sphinx-lint
        run: sphinx-lint --enable line-too-long --max-line-length 120
      - name: Run sphinx-build lint
        run: make html SPHINXOPTS="-W --keep-going -n"
